# Generated by Django 5.2.4 on 2025-08-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='priyopay_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
