# Generated by Django 5.2.4 on 2025-08-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfinancialinfo',
            name='student_file_bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
