# Generated by Django 5.2.4 on 2025-08-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentuser_priyopay_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfinancialinfo',
            name='family_contribution_usd',
        ),
        migrations.RemoveField(
            model_name='studentfinancialinfo',
            name='loan_required_usd',
        ),
        migrations.RemoveField(
            model_name='studentfinancialinfo',
            name='monthly_income_usd',
        ),
        migrations.RemoveField(
            model_name='studentfinancialinfo',
            name='savings_usd',
        ),
        migrations.RemoveField(
            model_name='studentfinancialinfo',
            name='yearly_income_usd',
        ),
        migrations.AddField(
            model_name='studentfinancialinfo',
            name='annual_family_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='studentfinancialinfo',
            name='estimated_income_in_cent_from_part_time_per_month',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='studentfinancialinfo',
            name='foreign_currency_purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfinancialinfo',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='studentfinancialinfo',
            name='other_funding_sources',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentfinancialinfo',
            name='purchased_currency_amount_in_cent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='studentfinancialinfo',
            name='remittance_by_other_channels',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfinancialinfo',
            name='savings_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='studentfinancialinfo',
            name='scholarship_amount_in_cent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='studentfinancialinfo',
            name='scholarship_period',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentfinancialinfo',
            name='scholarship_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentfinancialinfo',
            name='willing_to_return_to_bd',
            field=models.BooleanField(default=False),
        ),
    ]
